### ISSUE TITLE
Wrong spelling: Syntactically Awesome Style Sheet.

### ISSUE THREAD

**Issue by uchchwas1** [Asfak00/sass-learning#1]
Wrong spelling Syntactically Awesome Syle Sheet.
Correct spelling will be Syntactically Awesome Style Sheet.

**Comment by Asfak00** [comment]
Ok ✅

**Comment by Asfak00** [comment]
Your issue approved

**Comment by Asfak00** [comment]
This is a very small mistake of my typing 😁 thank you for remaind me it
